import { useEffect, useMemo, useRef, useState } from "react"
import { AlertTriangle, ArrowLeft, Braces, CheckCircle2, ChevronDown, ChevronRight, CircleStop, Columns3, Database, FileCode2, KeyRound, LoaderCircle, Play, Plus, RefreshCw, Search, ShieldCheck, Table2, Trash2, WandSparkles, XCircle } from "lucide-react"
import { databasesApi, type DatabaseConnection, type DatabaseSchema, type DatabaseTable, type QueryResult } from "@/api/databases"
import { Button } from "@/components/ui/button"
import { navigate } from "@/router/navigation"

type ConnectionState = "connecting" | "connected" | "error"
type ResultTab = "result" | "message"

export function DatabaseWorkspacePage({ databaseId }: { databaseId: number }) {
  const [connection, setConnection] = useState<DatabaseConnection | null>(null)
  const [schemas, setSchemas] = useState<DatabaseSchema[]>([])
  const [connectionState, setConnectionState] = useState<ConnectionState>("connecting")
  const [schemaError, setSchemaError] = useState("")
  const [filter, setFilter] = useState("")
  const [expandedSchemas, setExpandedSchemas] = useState<Set<string>>(new Set())
  const [expandedTables, setExpandedTables] = useState<Set<string>>(new Set())
  const [sidebarWidth, setSidebarWidth] = useState(270)
  const [editorHeight, setEditorHeight] = useState(310)
  const [sql, setSQL] = useState(() => localStorage.getItem(`easyssh.database.${databaseId}.sql`) ?? "-- 在这里输入 SQL\nSELECT 1;")
  const [result, setResult] = useState<QueryResult | null>(null)
  const [resultTab, setResultTab] = useState<ResultTab>("result")
  const [executing, setExecuting] = useState(false)
  const [queryError, setQueryError] = useState("")
  const [executedSQL, setExecutedSQL] = useState("")
  const editorRef = useRef<HTMLTextAreaElement>(null)
  const abortRef = useRef<AbortController | null>(null)

  useEffect(() => { databasesApi.get(databaseId).then(setConnection).catch((e: Error) => { setSchemaError(e.message); setConnectionState("error") }) }, [databaseId])
  useEffect(() => { const timer = window.setTimeout(() => localStorage.setItem(`easyssh.database.${databaseId}.sql`, sql), 300); return () => window.clearTimeout(timer) }, [databaseId, sql])
  useEffect(() => { void refreshSchema(); return () => abortRef.current?.abort() }, [databaseId])

  async function refreshSchema() {
    setConnectionState("connecting"); setSchemaError("")
    try { const data = await databasesApi.schema(databaseId); setSchemas(data.schemas); setExpandedSchemas(new Set(data.schemas.map((schema) => schema.name))); setConnectionState("connected") }
    catch (e) { setSchemaError((e as Error).message); setConnectionState("error") }
  }
  function chosenSQL() { const textarea = editorRef.current; if (textarea && textarea.selectionStart !== textarea.selectionEnd) return sql.slice(textarea.selectionStart, textarea.selectionEnd).trim(); return currentStatement(sql, textarea?.selectionStart ?? 0) }
  async function execute() {
    const statement = chosenSQL(); if (!statement || executing) return
    const warning = dangerousWarning(statement); if (warning && !window.confirm(warning)) return
    const controller = new AbortController(); abortRef.current = controller; setExecuting(true); setQueryError(""); setExecutedSQL(statement); setResultTab("result")
    try { const data = await databasesApi.execute(databaseId, statement, Boolean(warning), controller.signal); setResult(data); setConnectionState("connected"); if (data.kind === "command") { setResultTab("message"); void refreshSchema() } }
    catch (e) { setQueryError(controller.signal.aborted ? "查询已取消" : (e as Error).message); setResultTab("message") }
    finally { setExecuting(false); abortRef.current = null }
  }
  function insertTable(schema: string, table: DatabaseTable) { setSQL(`SELECT *\nFROM ${qualifiedName(connection?.type, schema, table.name)}\nLIMIT 100;`); editorRef.current?.focus() }
  function resizeSidebar(e: React.PointerEvent) { const startX = e.clientX, start = sidebarWidth; const move = (event: PointerEvent) => setSidebarWidth(Math.min(420, Math.max(210, start + event.clientX - startX))); const up = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up) }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up) }
  function resizeEditor(e: React.PointerEvent) { const startY = e.clientY, start = editorHeight; const move = (event: PointerEvent) => setEditorHeight(Math.min(window.innerHeight - 260, Math.max(180, start + event.clientY - startY))); const up = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up) }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up) }
  const visibleSchemas = useMemo(() => filterSchemas(schemas, filter), [schemas, filter])

  return <div className="flex h-svh flex-col overflow-hidden bg-background text-foreground">
    <header className="flex h-14 shrink-0 items-center gap-3 border-b px-4">
      <Button variant="ghost" size="icon-sm" title="返回数据库列表" onClick={() => navigate("/databases")}><ArrowLeft /></Button><div className="h-5 w-px bg-border" /><div className="grid size-8 place-items-center rounded-lg bg-foreground text-background"><Database className="size-4" /></div>
      <div className="min-w-0"><div className="flex items-center gap-2"><span className="truncate text-sm font-semibold">{connection?.name ?? "数据库工作台"}</span>{connection && <span className="rounded bg-muted px-1.5 py-0.5 text-[10px] font-medium uppercase text-muted-foreground">{connection.type === "postgres" ? "PostgreSQL" : connection.type}</span>}</div><div className="max-w-[420px] truncate text-[11px] text-muted-foreground">{connectionAddress(connection)}</div></div>
      {connection?.useSshTunnel && <span className="inline-flex items-center gap-1 rounded-md border px-2 py-1 text-[11px] text-muted-foreground"><ShieldCheck className="size-3" />SSH 隧道</span>}
      <div className="ml-auto flex items-center gap-2"><ConnectionBadge state={connectionState} /><Button variant="outline" size="sm" disabled={connectionState === "connecting"} onClick={() => void refreshSchema()}><RefreshCw className={connectionState === "connecting" ? "animate-spin" : ""} />刷新结构</Button></div>
    </header>
    <div className="flex min-h-0 flex-1">
      <aside className="flex shrink-0 flex-col border-r bg-muted/10" style={{ width: sidebarWidth }}><div className="flex h-11 items-center border-b px-3"><div className="text-xs font-semibold">数据库对象</div><span className="ml-auto text-[10px] text-muted-foreground">{schemas.reduce((count, schema) => count + schema.tables.length, 0)} 张表</span></div><div className="p-2"><div className="relative"><Search className="absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2 text-muted-foreground" /><input className="h-8 w-full rounded-md border bg-background pr-2 pl-8 text-xs outline-none focus:ring-2 focus:ring-ring/20" value={filter} onChange={(e) => setFilter(e.target.value)} placeholder="搜索表或字段..." /></div></div><div className="min-h-0 flex-1 overflow-auto px-2 pb-3">{connectionState === "connecting" && <SidebarNotice icon={<LoaderCircle className="animate-spin" />} text="正在读取数据库结构..." />}{connectionState === "error" && <SidebarNotice icon={<XCircle />} text={schemaError || "连接失败"} />}{connectionState === "connected" && visibleSchemas.length === 0 && <SidebarNotice icon={<Search />} text="没有匹配的表或字段" />}{visibleSchemas.map((schema) => <SchemaNode key={schema.name} schema={schema} databaseType={connection?.type} forceOpen={Boolean(filter)} expandedSchemas={expandedSchemas} setExpandedSchemas={setExpandedSchemas} expandedTables={expandedTables} setExpandedTables={setExpandedTables} onOpenTable={insertTable} />)}</div></aside>
      <div className="w-1 shrink-0 cursor-col-resize bg-transparent transition hover:bg-primary/20" onPointerDown={resizeSidebar} />
      <section className="flex min-w-0 flex-1 flex-col">
        <div className="flex h-10 shrink-0 items-end border-b bg-muted/15 px-2"><div className="flex h-9 min-w-36 items-center gap-2 rounded-t-md border border-b-background bg-background px-3 text-xs font-medium"><FileCode2 className="size-3.5 text-muted-foreground" />Query 1<span className="ml-auto size-1.5 rounded-full bg-amber-400" title="查询自动保存在本地" /></div><button className="mb-1 ml-1 rounded p-1.5 text-muted-foreground hover:bg-muted" title="后续支持多查询标签"><Plus className="size-3.5" /></button></div>
        <div className="relative shrink-0" style={{ height: editorHeight }}><div className="absolute inset-y-0 left-0 w-12 select-none overflow-hidden border-r bg-muted/15 pt-4 text-right font-mono text-xs leading-6 text-muted-foreground/60">{sql.split("\n").map((_, index) => <div className="pr-3" key={index}>{index + 1}</div>)}</div><textarea ref={editorRef} value={sql} spellCheck={false} onChange={(e) => setSQL(e.target.value)} onKeyDown={(e) => { if ((e.ctrlKey || e.metaKey) && e.key === "Enter") { e.preventDefault(); void execute() } }} className="absolute inset-0 resize-none bg-transparent py-4 pr-5 pl-16 font-mono text-[13px] leading-6 outline-none selection:bg-blue-500/20" aria-label="SQL 编辑器" /></div>
        <div className="flex h-11 shrink-0 items-center gap-1 border-y px-3"><Button size="sm" disabled={executing || !sql.trim()} onClick={() => void execute()}>{executing ? <LoaderCircle className="animate-spin" /> : <Play />}运行</Button><Button variant="ghost" size="sm" disabled={!executing} onClick={() => abortRef.current?.abort()}><CircleStop />停止</Button><div className="mx-1 h-5 w-px bg-border" /><Button variant="ghost" size="sm" disabled={executing} onClick={() => setSQL(formatSQL(sql))}><WandSparkles />格式化</Button><Button variant="ghost" size="sm" disabled={executing || !sql} onClick={() => setSQL("")}><Trash2 />清空</Button><div className="ml-auto text-[11px] text-muted-foreground">Ctrl / ⌘ + Enter 运行{result && <> · {result.durationMs} ms · {result.kind === "rows" ? `${result.rows.length} 行` : `影响 ${result.rowsAffected} 行`}</>}</div></div>
        <div className="h-1 shrink-0 cursor-row-resize bg-transparent transition hover:bg-primary/20" onPointerDown={resizeEditor} />
        <div className="flex min-h-0 flex-1 flex-col"><div className="flex h-10 shrink-0 items-end border-b px-3"><ResultTabButton active={resultTab === "result"} onClick={() => setResultTab("result")}>查询结果{result?.kind === "rows" && <span className="rounded bg-muted px-1.5 text-[10px]">{result.rows.length}</span>}</ResultTabButton><ResultTabButton active={resultTab === "message"} onClick={() => setResultTab("message")}>消息{queryError && <span className="size-1.5 rounded-full bg-red-500" />}</ResultTabButton></div><div className="min-h-0 flex-1 overflow-auto">{resultTab === "result" ? <Results result={result} executing={executing} /> : <Messages result={result} error={queryError} sql={executedSQL} />}</div></div>
      </section>
    </div>
  </div>
}

function SchemaNode({ schema, databaseType, forceOpen, expandedSchemas, setExpandedSchemas, expandedTables, setExpandedTables, onOpenTable }: { schema: DatabaseSchema; databaseType?: string; forceOpen: boolean; expandedSchemas: Set<string>; setExpandedSchemas: (value: Set<string>) => void; expandedTables: Set<string>; setExpandedTables: (value: Set<string>) => void; onOpenTable: (schema: string, table: DatabaseTable) => void }) {
  const schemaOpen = forceOpen || expandedSchemas.has(schema.name)
  const toggle = (set: Set<string>, key: string, update: (value: Set<string>) => void) => { const next = new Set(set); next.has(key) ? next.delete(key) : next.add(key); update(next) }
  return <div><button className="flex h-8 w-full items-center gap-1.5 rounded px-1 text-xs hover:bg-muted" onClick={() => toggle(expandedSchemas, schema.name, setExpandedSchemas)}>{schemaOpen ? <ChevronDown className="size-3.5" /> : <ChevronRight className="size-3.5" />}<Database className="size-3.5 text-blue-500" /><span className="truncate font-medium">{databaseType === "mysql" ? "表" : schema.name}</span><span className="ml-auto pr-1 text-[10px] text-muted-foreground">{schema.tables.length}</span></button>{schemaOpen && <div className="ml-3 border-l pl-1">{schema.tables.map((table) => { const key = `${schema.name}.${table.name}`, open = forceOpen || expandedTables.has(key); return <div key={key}><div className="group flex h-8 items-center"><button className="flex min-w-0 flex-1 items-center gap-1.5 rounded px-1 text-xs hover:bg-muted" onClick={() => toggle(expandedTables, key, setExpandedTables)} onDoubleClick={() => onOpenTable(schema.name, table)}>{open ? <ChevronDown className="size-3.5 shrink-0" /> : <ChevronRight className="size-3.5 shrink-0" />}<Table2 className="size-3.5 shrink-0 text-emerald-600" /><span className="truncate">{table.name}</span></button><button className="invisible mr-1 rounded p-1 text-muted-foreground hover:bg-muted group-hover:visible" title="生成 SELECT" onClick={() => onOpenTable(schema.name, table)}><Braces className="size-3" /></button></div>{open && <div className="ml-5 border-l pl-2">{table.columns.map((column) => <div key={column.name} className="flex h-7 items-center gap-1.5 text-[11px]"><span className="grid size-3.5 place-items-center">{column.primaryKey ? <KeyRound className="size-3 text-amber-500" /> : <Columns3 className="size-3 text-muted-foreground" />}</span><span className="min-w-0 flex-1 truncate">{column.name}</span><span className="max-w-20 truncate text-[10px] text-muted-foreground" title={column.type}>{column.type || "—"}</span></div>)}</div>}</div>})}</div>}</div>
}

function Results({ result, executing }: { result: QueryResult | null; executing: boolean }) {
  if (executing) return <Empty icon={<LoaderCircle className="animate-spin" />} title="正在执行查询" detail="可以点击停止取消当前查询。" />
  if (!result) return <Empty icon={<Table2 />} title="暂无查询结果" detail="运行 SQL 后，结果会显示在这里。" />
  if (result.kind === "command") return <Empty icon={<CheckCircle2 className="text-emerald-600" />} title="语句执行成功" detail={result.message} />
  return <div className="min-w-max"><table className="border-collapse text-left font-mono text-xs"><thead className="sticky top-0 z-10 bg-muted"><tr><th className="w-12 border-r border-b px-3 py-2 text-right font-normal text-muted-foreground">#</th>{result.columns.map((column, index) => <th key={`${column.name}-${index}`} className="min-w-32 border-r border-b px-3 py-2 font-medium"><div>{column.name}</div>{column.type && <div className="mt-0.5 text-[9px] font-normal text-muted-foreground">{column.type}</div>}</th>)}</tr></thead><tbody>{result.rows.map((row, rowIndex) => <tr key={rowIndex} className="hover:bg-muted/30"><td className="border-r border-b px-3 py-2 text-right text-muted-foreground">{rowIndex + 1}</td>{row.map((value, columnIndex) => <td key={columnIndex} className="max-w-md border-r border-b px-3 py-2"><Cell value={value} /></td>)}</tr>)}</tbody></table>{result.truncated && <div className="sticky left-0 border-t bg-amber-500/10 px-4 py-2 text-xs text-amber-700">结果超过 500 行，仅展示前 500 行。</div>}</div>
}
function Cell({ value }: { value: unknown }) { if (value === null) return <span className="italic text-muted-foreground/60">NULL</span>; if (typeof value === "object") return <span title={JSON.stringify(value)}>{JSON.stringify(value)}</span>; const text = String(value); return <span className="block max-w-md truncate" title={text}>{typeof value === "boolean" ? (value ? "true" : "false") : text}</span> }
function Messages({ result, error, sql }: { result: QueryResult | null; error: string; sql: string }) { return <div className="p-5 font-mono text-xs">{error ? <div className="flex items-start gap-3 rounded-lg border border-red-500/20 bg-red-500/5 p-4 text-red-600"><AlertTriangle className="mt-0.5 size-4 shrink-0" /><div><div className="font-semibold">执行失败</div><div className="mt-2 whitespace-pre-wrap break-all">{error}</div></div></div> : result ? <div className="flex items-start gap-3 rounded-lg border p-4"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600" /><div><div className="font-semibold">{result.message}</div><div className="mt-2 text-muted-foreground">耗时 {result.durationMs} ms</div></div></div> : <div className="text-muted-foreground">查询执行信息会显示在这里。</div>}{sql && <div className="mt-4"><div className="mb-2 text-[10px] font-semibold tracking-wider text-muted-foreground uppercase">Executed SQL</div><pre className="max-h-32 overflow-auto whitespace-pre-wrap rounded-lg bg-muted p-3">{sql}</pre></div>}</div> }
function ConnectionBadge({ state }: { state: ConnectionState }) { const values = { connecting: ["bg-amber-500", "连接中"], connected: ["bg-emerald-500", "已连接"], error: ["bg-red-500", "连接失败"] }[state]; return <span className="inline-flex items-center gap-2 rounded-full bg-muted px-2.5 py-1 text-[11px]"><span className={`size-1.5 rounded-full ${values[0]}`} />{values[1]}</span> }
function ResultTabButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`flex h-10 items-center gap-2 border-b-2 px-3 text-xs ${active ? "border-foreground font-medium" : "border-transparent text-muted-foreground"}`}>{children}</button> }
function SidebarNotice({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flex flex-col items-center gap-2 px-3 py-10 text-center text-xs text-muted-foreground"><span className="[&_svg]:size-5">{icon}</span>{text}</div> }
function Empty({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="grid h-full min-h-40 place-items-center text-center"><div><div className="mx-auto grid size-10 place-items-center rounded-xl bg-muted text-muted-foreground [&_svg]:size-5">{icon}</div><div className="mt-3 text-sm font-medium">{title}</div><div className="mt-1 text-xs text-muted-foreground">{detail}</div></div></div> }
function filterSchemas(schemas: DatabaseSchema[], filter: string) { const needle = filter.trim().toLowerCase(); if (!needle) return schemas; return schemas.map((schema) => ({ ...schema, tables: schema.tables.map((table) => ({ ...table, columns: table.columns.filter((column) => table.name.toLowerCase().includes(needle) || column.name.toLowerCase().includes(needle)) })).filter((table) => table.name.toLowerCase().includes(needle) || table.columns.length) })).filter((schema) => schema.name.toLowerCase().includes(needle) || schema.tables.length) }
function connectionAddress(connection: DatabaseConnection | null) { if (!connection) return "正在读取连接信息..."; return connection.type === "sqlite" ? connection.sqlitePath : `${connection.username}@${connection.address}:${connection.port}/${connection.databaseName}` }
function quoteIdentifier(type: string | undefined, value: string) { return type === "mysql" ? `\`${value.replaceAll("`", "``")}\`` : `"${value.replaceAll('"', '""')}"` }
function qualifiedName(type: string | undefined, schema: string, table: string) { if (type === "sqlite" || type === "mysql") return quoteIdentifier(type, table); return `${quoteIdentifier(type, schema)}.${quoteIdentifier(type, table)}` }
function currentStatement(value: string, cursor: number) { const before = value.lastIndexOf(";", Math.max(0, cursor - 1)); const after = value.indexOf(";", cursor); return value.slice(before + 1, after < 0 ? value.length : after + 1).trim() || value.trim() }
function dangerousWarning(value: string) { const normalized = value.replace(/^\s*(?:(?:--[^\n]*(?:\n|$))|(?:\/\*[\s\S]*?\*\/))*\s*/i, "").toUpperCase(); if (/\b(DROP|TRUNCATE)\b/.test(normalized)) return "该 SQL 包含 DROP 或 TRUNCATE，将删除数据库对象或数据。确认继续执行吗？"; if (/\b(UPDATE|DELETE\s+FROM)\b/.test(normalized) && !/\bWHERE\b/.test(normalized)) return "该 SQL 是不含 WHERE 条件的 UPDATE 或 DELETE，可能影响整张表。确认继续执行吗？"; return "" }
function formatSQL(value: string) { return value.trim().replace(/\s+\b(FROM|WHERE|LEFT JOIN|RIGHT JOIN|INNER JOIN|OUTER JOIN|GROUP BY|ORDER BY|HAVING|LIMIT|VALUES|SET)\b/gi, "\n$1").replace(/\b(select|from|where|insert into|update|delete from|join|left join|right join|inner join|group by|order by|having|limit|values|set|as|and|or|null|is|not)\b/gi, (word) => word.toUpperCase()) }

export default DatabaseWorkspacePage
